language: haskell

ghc:
  - 7.6
  - 7.8

env:
  - lower_bound_dependencies=1
  - 

install:
  # Set up the Shell to treat the semicolon as &&
  - set -o pipefail && set -e
  # Install the lower bound dependencies
  - if [ $lower_bound_dependencies -eq 1 ];
    then
      cabal install "transformers == 0.2.*";
      cabal install "text == 1.0.*";
      cabal install "attoparsec == 0.10.*";
      cabal install "time == 1.4.*";
    fi;
  - cabal install happy # a "haskell-src-exts" implicit dependency workaround
  - cabal install --only-dependencies --enable-tests --enable-benchmarks --force-reinstalls

script:
  - cabal configure --enable-tests --enable-benchmarks
  - cabal build
  - cabal test --show-details=always
